spring:
  scheduled:
    cache-update-period: 50000
  jackson:
    time-zone: Europe/Kiev
  data:
    mongodb:
      uri: mongodb://localhost:27017/amazon-task

jwt:
  token:
    secretKey: n0rth88n0rth88n0rth88n0rth88n0rth88n0rth88side
    expired: 900000

init:
  data:
    file:
      path: file:test_report.json

